# run: conda env create -n <name> --file environment.yml
# conda env create -n trOCR --file environment.yml
name: trOCR 
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch::pytorch=1.10.2
  - pytorch::torchvision=0.11.3
  - pytorch::torchaudio=0.10.2
  - cudatoolkit=11.3

  - ipykernel
  - jupyter
  - nb_conda_kernels
  - ipywidgets

  - pip
  - pip:
      - pillow==9.0.1
      - transformers==4.30.0
      - sentencepiece==0.1.96
      - typer==0.4.1
      - protobuf==3.20.0
      - numpy==1.26.4
